//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_choosecone
    {
        public System.Guid id { get; set; }
        public string w_cone_choice { get; set; }
    }
}
